### PR TITLE
Fix the labelSelector capitalization issue and set memberSelector to …

### LINKED ISSUE #161: Hypernode memberSelector validation rule error
**Describe the bug**

Image
Currently, the kubebuilder validation in the memberSelector of hypernode is written to ensure that all three match cases cannot exist simultaneously, but the actual requirement is that only one should exist. 

**Expected behavior**
The current implementation does not check for the case where two matches exist at the same time. We should modify to like this:
```
// +kubebuilder:validation:XValidation:rule="has(self.exactMatch) || has(self.regexMatch) || has(self.labelMatch)",message="Either ExactMatch or RegexMatch or LabelMatch must be specified"
// +kubebuilder:validation:XValidation:rule="count([has(self.exactMatch), has(self.regexMatch), has(self.labelMatch)]) == 1",message="Only one of ExactMatch, RegexMatch, or LabelMatch can be specified"
```

### PR DESCRIPTION
**Pull request by JesseStutler**
Fix #161

1. Use ternary expression method to verify that memerSelector can only select one of three matching types, if more than two matching types are found, creation is rejected
2. Besides, fix the issue of labelMatch being in uppercase, which causes a compilation error

### validation
Create a hypernode that specifies both exactMatch and regexMatch, declined by the api-server:
image
image

### CODE REVIEW

File: pkg/apis/topology/v1alpha1/hypernode_types.go [hunk 1]
```diff
@@ -95,8 +95,8 @@ type MemberSpec struct {
 //		   regexMatch:
 //		     pattern: "^node-[0-9]+$"
 //
```
Comment (Monokaix) [inline pkg/apis/topology/v1alpha1/hypernode_types.go:97]: better add an example of label match.

Comment (JesseStutler) [reply pkg/apis/topology/v1alpha1/hypernode_types.go:97]: Done

**Review by kevin-wangzefeng — COMMENTED** [review]
/approve
